name: DeathArena
main: DA.DeathArenaMain
version: 0.1
commands:
    class:
        usage:
        description:
    configure:
        usage:
        description:
    start:
        usage:
        description:
    summonboss:
        usage:
        description: